### ISSUE TITLE
Tables don't exist

### ISSUE THREAD

**Issue by Billos** [intri-in/manage-my-damn-life-nextjs#177]
Hello, I'm running the project with a docker compose, and I have the following errors

```
  ▲ Next.js 13.5.6
  - Local:        http://b69402796cfd:3000
  - Network:      http://172.16.9.32:3000
 ✓ Ready in 166ms
Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
checkSSIDValidityError: Table 'mmdl.ssid_table' doesn't exist
checkSSIDValidityError: Table 'mmdl.ssid_table' doesn't exist
Executing (default): SHOW TABLES
[]
installed false
checkSSIDValidityError: Table 'mmdl.ssid_table' doesn't exist
Error: Table 'mmdl.settings' doesn't exist
    at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/app/node_modules/mysql2/lib/connection.js:492:32)
    at PacketParser.onPacket (/app/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/app/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10) {
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlState: '42S02',
  sqlMessage: "Table 'mmdl.settings' doesn't exist",
  sql: "SELECT * FROM settings WHERE name='GLOBAL_DISABLE_USER_REGISTRATION'"
}
Error: 'sharp' is required to be installed in standalone mode for the image optimization to function correctly. Read more at: https://nextjs.org/docs/messages/sharp-missing-in-production
Error: Table 'mmdl.settings' doesn't exist
    at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/app/node_modules/mysql2/lib/connection.js:492:32)
    at PacketParser.onPacket (/app/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/app/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10) {
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlState: '42S02',
  sqlMessage: "Table 'mmdl.settings' doesn't exist",
  sql: "SELECT * FROM settings WHERE name='GLOBAL_DISABLE_USER_REGISTRATION'"
}
Error: Table 'mmdl.users' doesn't exist
    at Packet.asError (/app/node_modules/mysql2/lib/packets/packet.js:728:17)
    at Query.execute (/app/node_modules/mysql2/lib/commands/command.js:29:26)
    at Connection.handlePacket (/app/node_modules/mysql2/lib/connection.js:492:32)
    at PacketParser.onPacket (/app/node_modules/mysql2/lib/connection.js:97:12)
    at PacketParser.executeStart (/app/node_modules/mysql2/lib/packet_parser.js:75:16)
    at Socket.<anonymous> (/app/node_modules/mysql2/lib/connection.js:104:25)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10) {
  code: 'ER_NO_SUCH_TABLE',
  errno: 1146,
  sqlState: '42S02',
  sqlMessage: "Table 'mmdl.users' doesn't exist",
  sql: "SELECT * FROM users WHERE username= 'billos'"
}
```

Is there something I'm missing in the installation ?

**Comment by intri-in** [comment]
It looks like MMDL can't connect to your database. Did you set the db settings in your .env file?

Can you go to http://your-ip/install/ and see if there are any error messages ?
